@extends('layout.admin')

@section('page_title', 'Appointment Reports')

@section('content')
    <div class="container-fluid p-4">
        <!-- Header Controls -->
        <div class="d-flex justify-content-between align-items-center mb-4 d-print-none">
            <div>
                <h2 class="fw-bold mb-0">Daily & Weekly Reports</h2>
                <p class="text-muted small">Municipal Veterinary Office Appointment Tracking</p>
            </div>
            <div>
                <!-- Date Filter Dropdown -->
                <div class="btn-group me-2">
                    <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <i data-lucide="calendar" class="me-2 size-16"></i> Range: {{ ucfirst($range) }}
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item"
                                href="{{ route('admin.reports.appointments', ['range' => 'daily']) }}">Daily
                                Appointments</a></li>
                        <li><a class="dropdown-item"
                                href="{{ route('admin.reports.appointments', ['range' => 'weekly']) }}">Weekly
                                Appointments</a></li>
                        <li><a class="dropdown-item"
                                href="{{ route('admin.reports.appointments', ['range' => 'monthly']) }}">Monthly
                                Appointments</a></li>
                    </ul>
                </div>

                <button onclick="window.print()" class="btn btn-orange fw-bold shadow-sm">
                    <i data-lucide="printer" class="me-2 size-16"></i> Print Report
                </button>
            </div>
        </div>

        <!-- Official Report Header (Only visible in Print) -->
        <div class="report-header text-center mb-5 border-bottom pb-4 d-none d-print-block"
            style="color: black !important;">
            <div class="d-flex justify-content-center align-items-center mb-3">
                <div class="text-center">
                    <h5 class="mb-0 fw-bold text-uppercase">Republic of the Philippines</h5>
                    <h6 class="mb-0 text-uppercase">Province of Bulacan</h6>
                    <h6 class="mb-0 text-uppercase">City of Meycauayan</h6>
                    <h4 class="mt-2 fw-bold">Office of the City Veterinarian (PawCare)</h4>
                </div>
            </div>
            <h3 class="fw-bold text-decoration-underline text-uppercase mt-4">{{ ucfirst($range) }} Appointment Report</h3>
            <p class="mb-0">Date Covered: {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} -
                {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</p>
            <p class="mb-0 small text-muted">Generated by: {{ Auth::user()->name }} ({{ now()->format('Y-m-d h:i A') }})</p>
        </div>

        <!-- Analytics Summary / Metric Cards -->
        <div class="row g-4 mb-4">
            <div class="col-md-3">
                <div class="card bg-primary text-white border-0 shadow-sm p-3 printable-card">
                    <h6 class="text-uppercase fw-bold mb-1">Total Bookings</h6>
                    <h2 class="mb-0 fw-bold">{{ $summary['total'] }}</h2>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-success text-white border-0 shadow-sm p-3 printable-card">
                    <h6 class="text-uppercase fw-bold mb-1">Completed</h6>
                    <h2 class="mb-0 fw-bold">{{ $summary['completed'] }}</h2>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-danger text-white border-0 shadow-sm p-3 printable-card">
                    <h6 class="text-uppercase fw-bold mb-1">Cancelled</h6>
                    <h2 class="mb-0 fw-bold">{{ $summary['cancelled'] }}</h2>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-warning text-dark border-0 shadow-sm p-3 printable-card">
                    <h6 class="text-uppercase fw-bold mb-1">Missed</h6>
                    <h2 class="mb-0 fw-bold">{{ $summary['missed'] }}</h2>
                </div>
            </div>
        </div>

        <!-- Detailed List Table -->
        <div class="card border-0 shadow-sm rounded-4">
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover align-middle mb-0 report-table">
                        <thead class="bg-light">
                            <tr class="text-uppercase small fw-bold text-muted">
                                <th class="ps-4">Date & Time</th>
                                <th>Owner Name</th>
                                <th>Pet Name</th>
                                <th>Species</th>
                                <th>Service Type</th>
                                <th class="pe-4 text-center">Final Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($appointments as $appt)
                                <tr>
                                    <td class="ps-4">
                                        <span
                                            class="fw-bold">{{ \Carbon\Carbon::parse($appt->appointment_date)->format('M d, Y') }}</span><br>
                                        <small
                                            class="text-muted">{{ date('h:i A', strtotime($appt->appointment_time)) }}</small>
                                    </td>
                                    <td>{{ $appt->user->name ?? 'Unknown' }}</td>
                                    <td class="fw-bold">{{ $appt->pet_name }}</td>
                                    <td>{{ ucfirst($appt->species) }}</td>
                                    <td>{{ ucfirst($appt->service_type) }}</td>
                                    <td class="pe-4 text-center">
                                        @if(in_array($appt->status, ['completed', 'Done']))
                                            <span class="badge bg-success shadow-none">Completed</span>
                                        @elseif($appt->status === 'cancelled')
                                            <span class="badge bg-danger shadow-none">Cancelled</span>
                                        @elseif($appt->status === 'missed')
                                            <span class="badge bg-warning text-dark shadow-none">Missed</span>
                                        @else
                                            <span class="badge bg-secondary shadow-none">{{ ucfirst($appt->status) }}</span>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6" class="text-center py-4 text-muted">No appointments found for this period.
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <style>
        /* Print Landscape Formatting */
        @media print {

            /* Hide navigational UI */
            #sidebar,
            header,
            nav,
            .d-print-none,
            .btn {
                display: none !important;
            }

            /* Layout properties */
            @page {
                size: landscape;
                margin: 10mm;
            }

            body {
                margin: 0;
                padding: 0;
                background: white !important;
                font-size: 11pt;
                /* Professional print styling */
            }

            /* Table styling for official reports */
            .report-table {
                width: 100% !important;
                border-collapse: collapse !important;
            }

            .report-table th,
            .report-table td {
                border: 1px solid black !important;
                padding: 8px !important;
                color: black !important;
            }

            tr {
                page-break-inside: avoid;
            }

            /* Print styling for metric cards */
            .printable-card {
                border: 1px solid #000 !important;
                color: #000 !important;
                background-color: transparent !important;
                box-shadow: none !important;
            }
        }
    </style>
@endsection
