@extends('layout.admin')

@section('page_title', 'Vaccine Inventory Reports')

@section('content')
    <div class="container-fluid p-4">
        <!-- Header Controls -->
        <div class="d-flex justify-content-between align-items-center mb-4 d-print-none">
            <div>
                <h2 class="fw-bold mb-0">Vaccine & Stock Analysis</h2>
                <p class="text-muted small">Municipal Stock Movements & Expirations</p>
            </div>
            <div>
                <button onclick="window.print()" class="btn btn-orange fw-bold shadow-sm">
                    <i data-lucide="printer" class="me-2 size-16"></i> Print Report
                </button>
            </div>
        </div>

        <!-- Official Report Header (Only visible in Print) -->
        <div class="report-header text-center mb-5 border-bottom pb-4 d-none d-print-block"
            style="color: black !important;">
            <div class="d-flex justify-content-center align-items-center mb-3">
                <div class="text-center">
                    <h5 class="mb-0 fw-bold text-uppercase">Republic of the Philippines</h5>
                    <h6 class="mb-0 text-uppercase">Province of Bulacan</h6>
                    <h6 class="mb-0 text-uppercase">City of Meycauayan</h6>
                    <h4 class="mt-2 fw-bold">Office of the City Veterinarian (PawCare)</h4>
                </div>
            </div>
            <h3 class="fw-bold text-decoration-underline text-uppercase mt-4">Official Inventory Control Report</h3>
            <p class="mb-0">Date Generated: {{ now()->format('F d, Y h:i A') }}</p>
            <p class="mb-0 small text-muted">Generated by: {{ Auth::user()->name }}</p>
        </div>

        <div class="row g-4 mb-4">
            <!-- Stock Movement Section -->
            <div class="col-md-7">
                <div class="card border-0 shadow-sm rounded-4 h-100">
                    <div class="card-header bg-white border-bottom-0 pt-4 pb-0">
                        <h5 class="fw-bold mb-0">Current Vaccine Stock</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover align-middle report-table">
                                <thead class="bg-light">
                                    <tr class="small text-uppercase fw-bold text-muted">
                                        <th>Vaccine Line</th>
                                        <th>Batch No.</th>
                                        <th>Low Stock Alert</th>
                                        <th class="text-end">Current Stock</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($vaccines as $vax)
                                        <tr>
                                            <td class="fw-bold">{{ $vax->name }}</td>
                                            <td>{{ $vax->batch_no ?? 'N/A' }}</td>
                                            <td>{{ $vax->low_stock_threshold }} doses</td>
                                            <td
                                                class="text-end fw-bold {{ $vax->is_low_stock ? 'text-danger' : 'text-success' }}">
                                                {{ $vax->stock }}
                                                @if($vax->is_low_stock)
                                                    <i class="bi bi-exclamation-triangle-fill ms-1"></i>
                                                @endif
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="4" class="text-center py-3">No inventory data configured.</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Expiry Tracking Section -->
            <div class="col-md-5">
                <div class="card border-0 shadow-sm bg-danger-subtle rounded-4 mb-4 h-50">
                    <div class="card-body">
                        <h6 class="fw-bold text-danger text-uppercase mb-3"><i class="bi bi-calendar-x me-2"></i> Expiry
                            Warnings (30 Days)</h6>
                        <ul class="list-group list-group-flush rounded border d-print-table"
                            style="background: transparent;">
                            @forelse($expiringVaccines as $exp)
                                <li class="list-group-item bg-transparent d-flex justify-content-between align-items-center">
                                    <div>
                                        <strong>{{ $exp->name }}</strong><br>
                                        <small class="text-muted">Batch: {{ $exp->batch_no }}</small>
                                    </div>
                                    <span class="badge bg-danger">Exp:
                                        {{ \Carbon\Carbon::parse($exp->expiry_date)->format('M d, Y') }}</span>
                                </li>
                            @empty
                                <li class="list-group-item bg-transparent text-center text-muted py-3">
                                    <i class="bi bi-check-circle text-success me-1"></i> No vaccines expiring soon.
                                </li>
                            @endforelse
                        </ul>
                    </div>
                </div>

                <!-- Monthly Usage Logs -->
                <div class="card border-0 shadow-sm bg-primary-subtle rounded-4 h-50 pt-2">
                    <div class="card-body">
                        <h6 class="fw-bold text-primary text-uppercase mb-3"><i class="bi bi-activity me-2"></i> Monthly
                            Usage Logistics</h6>
                        <p class="small text-muted mb-2">Total doses administered across {{ now()->format('F Y') }}:</p>
                        <div class="table-responsive">
                            <table class="table table-sm table-borderless d-print-table">
                                <tbody>
                                    @forelse($usageLogs as $log)
                                        <tr>
                                            <td class="fw-medium">{{ $log->vaccine_name }}</td>
                                            <td class="text-end fw-bold">{{ $log->total_used }} doses</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="2" class="text-muted text-center pt-3">No vaccines used this month.
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        /* Print Landscape Formatting */
        @media print {

            #sidebar,
            header,
            nav,
            .d-print-none,
            .btn {
                display: none !important;
            }

            @page {
                size: landscape;
                margin: 10mm;
            }

            body {
                background: white !important;
                font-size: 11pt;
            }

            .report-table,
            .d-print-table {
                width: 100% !important;
                border-collapse: collapse !important;
            }

            .report-table th,
            .report-table td {
                border: 1px solid black !important;
                padding: 8px !important;
                color: black !important;
            }

            /* Print clear borders */
            .card {
                border: none !important;
                border-radius: 0 !important;
                box-shadow: none !important;
                background: transparent !important;
            }

            .text-danger {
                color: #dc3545 !important;
                font-weight: bold;
            }
        }
    </style>
@endsection
